// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: proto/users.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// User message
type User struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Role           string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	PasswordHash   string                 `protobuf:"bytes,4,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Percentage     *float64               `protobuf:"fixed64,5,opt,name=percentage,proto3,oneof" json:"percentage,omitempty"`
	IsTemplateUser bool                   `protobuf:"varint,6,opt,name=is_template_user,json=isTemplateUser,proto3" json:"is_template_user,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt      *int64                 `protobuf:"varint,9,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	SyncVersion    int32                  `protobuf:"varint,10,opt,name=sync_version,json=syncVersion,proto3" json:"sync_version,omitempty"`
	LastSyncedAt   *int64                 `protobuf:"varint,11,opt,name=last_synced_at,json=lastSyncedAt,proto3,oneof" json:"last_synced_at,omitempty"`
	NeedsSync      bool                   `protobuf:"varint,12,opt,name=needs_sync,json=needsSync,proto3" json:"needs_sync,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_proto_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetPercentage() float64 {
	if x != nil && x.Percentage != nil {
		return *x.Percentage
	}
	return 0
}

func (x *User) GetIsTemplateUser() bool {
	if x != nil {
		return x.IsTemplateUser
	}
	return false
}

func (x *User) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *User) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *User) GetDeletedAt() int64 {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return 0
}

func (x *User) GetSyncVersion() int32 {
	if x != nil {
		return x.SyncVersion
	}
	return 0
}

func (x *User) GetLastSyncedAt() int64 {
	if x != nil && x.LastSyncedAt != nil {
		return *x.LastSyncedAt
	}
	return 0
}

func (x *User) GetNeedsSync() bool {
	if x != nil {
		return x.NeedsSync
	}
	return false
}

// Template message
type UserTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	DeletedAt     *int64                 `protobuf:"varint,7,opt,name=deleted_at,json=deletedAt,proto3,oneof" json:"deleted_at,omitempty"`
	SyncVersion   int32                  `protobuf:"varint,8,opt,name=sync_version,json=syncVersion,proto3" json:"sync_version,omitempty"`
	LastSyncedAt  *int64                 `protobuf:"varint,9,opt,name=last_synced_at,json=lastSyncedAt,proto3,oneof" json:"last_synced_at,omitempty"`
	NeedsSync     bool                   `protobuf:"varint,10,opt,name=needs_sync,json=needsSync,proto3" json:"needs_sync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTemplate) Reset() {
	*x = UserTemplate{}
	mi := &file_proto_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTemplate) ProtoMessage() {}

func (x *UserTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTemplate.ProtoReflect.Descriptor instead.
func (*UserTemplate) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{1}
}

func (x *UserTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserTemplate) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserTemplate) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *UserTemplate) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

func (x *UserTemplate) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *UserTemplate) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *UserTemplate) GetDeletedAt() int64 {
	if x != nil && x.DeletedAt != nil {
		return *x.DeletedAt
	}
	return 0
}

func (x *UserTemplate) GetSyncVersion() int32 {
	if x != nil {
		return x.SyncVersion
	}
	return 0
}

func (x *UserTemplate) GetLastSyncedAt() int64 {
	if x != nil && x.LastSyncedAt != nil {
		return *x.LastSyncedAt
	}
	return 0
}

func (x *UserTemplate) GetNeedsSync() bool {
	if x != nil {
		return x.NeedsSync
	}
	return false
}

// Sync Users Request
type SyncUsersRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastSyncTimestamp int64                  `protobuf:"varint,1,opt,name=last_sync_timestamp,json=lastSyncTimestamp,proto3" json:"last_sync_timestamp,omitempty"`
	LocalChanges      []*User                `protobuf:"bytes,2,rep,name=local_changes,json=localChanges,proto3" json:"local_changes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncUsersRequest) Reset() {
	*x = SyncUsersRequest{}
	mi := &file_proto_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUsersRequest) ProtoMessage() {}

func (x *SyncUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUsersRequest.ProtoReflect.Descriptor instead.
func (*SyncUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{2}
}

func (x *SyncUsersRequest) GetLastSyncTimestamp() int64 {
	if x != nil {
		return x.LastSyncTimestamp
	}
	return 0
}

func (x *SyncUsersRequest) GetLocalChanges() []*User {
	if x != nil {
		return x.LocalChanges
	}
	return nil
}

// Sync Users Response
type SyncUsersResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerUpdates   []*User                `protobuf:"bytes,1,rep,name=server_updates,json=serverUpdates,proto3" json:"server_updates,omitempty"`
	DeletedIds      []string               `protobuf:"bytes,2,rep,name=deleted_ids,json=deletedIds,proto3" json:"deleted_ids,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,3,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncUsersResponse) Reset() {
	*x = SyncUsersResponse{}
	mi := &file_proto_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncUsersResponse) ProtoMessage() {}

func (x *SyncUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncUsersResponse.ProtoReflect.Descriptor instead.
func (*SyncUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{3}
}

func (x *SyncUsersResponse) GetServerUpdates() []*User {
	if x != nil {
		return x.ServerUpdates
	}
	return nil
}

func (x *SyncUsersResponse) GetDeletedIds() []string {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

func (x *SyncUsersResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// Sync Templates Request
type SyncTemplatesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LastSyncTimestamp int64                  `protobuf:"varint,1,opt,name=last_sync_timestamp,json=lastSyncTimestamp,proto3" json:"last_sync_timestamp,omitempty"`
	LocalChanges      []*UserTemplate        `protobuf:"bytes,2,rep,name=local_changes,json=localChanges,proto3" json:"local_changes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SyncTemplatesRequest) Reset() {
	*x = SyncTemplatesRequest{}
	mi := &file_proto_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTemplatesRequest) ProtoMessage() {}

func (x *SyncTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTemplatesRequest.ProtoReflect.Descriptor instead.
func (*SyncTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{4}
}

func (x *SyncTemplatesRequest) GetLastSyncTimestamp() int64 {
	if x != nil {
		return x.LastSyncTimestamp
	}
	return 0
}

func (x *SyncTemplatesRequest) GetLocalChanges() []*UserTemplate {
	if x != nil {
		return x.LocalChanges
	}
	return nil
}

// Sync Templates Response
type SyncTemplatesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServerUpdates   []*UserTemplate        `protobuf:"bytes,1,rep,name=server_updates,json=serverUpdates,proto3" json:"server_updates,omitempty"`
	DeletedIds      []string               `protobuf:"bytes,2,rep,name=deleted_ids,json=deletedIds,proto3" json:"deleted_ids,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,3,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncTemplatesResponse) Reset() {
	*x = SyncTemplatesResponse{}
	mi := &file_proto_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncTemplatesResponse) ProtoMessage() {}

func (x *SyncTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncTemplatesResponse.ProtoReflect.Descriptor instead.
func (*SyncTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{5}
}

func (x *SyncTemplatesResponse) GetServerUpdates() []*UserTemplate {
	if x != nil {
		return x.ServerUpdates
	}
	return nil
}

func (x *SyncTemplatesResponse) GetDeletedIds() []string {
	if x != nil {
		return x.DeletedIds
	}
	return nil
}

func (x *SyncTemplatesResponse) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// Get Users Request
type GetUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersRequest) Reset() {
	*x = GetUsersRequest{}
	mi := &file_proto_users_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersRequest) ProtoMessage() {}

func (x *GetUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersRequest.ProtoReflect.Descriptor instead.
func (*GetUsersRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{6}
}

// Get Users Response
type GetUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersResponse) Reset() {
	*x = GetUsersResponse{}
	mi := &file_proto_users_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersResponse) ProtoMessage() {}

func (x *GetUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersResponse.ProtoReflect.Descriptor instead.
func (*GetUsersResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{7}
}

func (x *GetUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

// Get Templates Request
type GetTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplatesRequest) Reset() {
	*x = GetTemplatesRequest{}
	mi := &file_proto_users_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplatesRequest) ProtoMessage() {}

func (x *GetTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplatesRequest.ProtoReflect.Descriptor instead.
func (*GetTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{8}
}

// Get Templates Response
type GetTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*UserTemplate        `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTemplatesResponse) Reset() {
	*x = GetTemplatesResponse{}
	mi := &file_proto_users_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTemplatesResponse) ProtoMessage() {}

func (x *GetTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTemplatesResponse.ProtoReflect.Descriptor instead.
func (*GetTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{9}
}

func (x *GetTemplatesResponse) GetTemplates() []*UserTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

// Delete User Request
type DeleteUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserRequest) Reset() {
	*x = DeleteUserRequest{}
	mi := &file_proto_users_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserRequest) ProtoMessage() {}

func (x *DeleteUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteUserRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Delete User Response
type DeleteUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserResponse) Reset() {
	*x = DeleteUserResponse{}
	mi := &file_proto_users_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserResponse) ProtoMessage() {}

func (x *DeleteUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Delete Template Request
type DeleteTemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateRequest) Reset() {
	*x = DeleteTemplateRequest{}
	mi := &file_proto_users_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateRequest) ProtoMessage() {}

func (x *DeleteTemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateRequest.ProtoReflect.Descriptor instead.
func (*DeleteTemplateRequest) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteTemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Delete Template Response
type DeleteTemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTemplateResponse) Reset() {
	*x = DeleteTemplateResponse{}
	mi := &file_proto_users_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTemplateResponse) ProtoMessage() {}

func (x *DeleteTemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_users_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTemplateResponse.ProtoReflect.Descriptor instead.
func (*DeleteTemplateResponse) Descriptor() ([]byte, []int) {
	return file_proto_users_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteTemplateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_users_proto protoreflect.FileDescriptor

const file_proto_users_proto_rawDesc = "" +
	"\n" +
	"\x11proto/users.proto\x12\x0emedicore.users\"\xb2\x03\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12#\n" +
	"\rpassword_hash\x18\x04 \x01(\tR\fpasswordHash\x12#\n" +
	"\n" +
	"percentage\x18\x05 \x01(\x01H\x00R\n" +
	"percentage\x88\x01\x01\x12(\n" +
	"\x10is_template_user\x18\x06 \x01(\bR\x0eisTemplateUser\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\t \x01(\x03H\x01R\tdeletedAt\x88\x01\x01\x12!\n" +
	"\fsync_version\x18\n" +
	" \x01(\x05R\vsyncVersion\x12)\n" +
	"\x0elast_synced_at\x18\v \x01(\x03H\x02R\flastSyncedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"needs_sync\x18\f \x01(\bR\tneedsSyncB\r\n" +
	"\v_percentageB\r\n" +
	"\v_deleted_atB\x11\n" +
	"\x0f_last_synced_at\"\xe8\x02\n" +
	"\fUserTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03R\tupdatedAt\x12\"\n" +
	"\n" +
	"deleted_at\x18\a \x01(\x03H\x00R\tdeletedAt\x88\x01\x01\x12!\n" +
	"\fsync_version\x18\b \x01(\x05R\vsyncVersion\x12)\n" +
	"\x0elast_synced_at\x18\t \x01(\x03H\x01R\flastSyncedAt\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"needs_sync\x18\n" +
	" \x01(\bR\tneedsSyncB\r\n" +
	"\v_deleted_atB\x11\n" +
	"\x0f_last_synced_at\"}\n" +
	"\x10SyncUsersRequest\x12.\n" +
	"\x13last_sync_timestamp\x18\x01 \x01(\x03R\x11lastSyncTimestamp\x129\n" +
	"\rlocal_changes\x18\x02 \x03(\v2\x14.medicore.users.UserR\flocalChanges\"\x9c\x01\n" +
	"\x11SyncUsersResponse\x12;\n" +
	"\x0eserver_updates\x18\x01 \x03(\v2\x14.medicore.users.UserR\rserverUpdates\x12\x1f\n" +
	"\vdeleted_ids\x18\x02 \x03(\tR\n" +
	"deletedIds\x12)\n" +
	"\x10server_timestamp\x18\x03 \x01(\x03R\x0fserverTimestamp\"\x89\x01\n" +
	"\x14SyncTemplatesRequest\x12.\n" +
	"\x13last_sync_timestamp\x18\x01 \x01(\x03R\x11lastSyncTimestamp\x12A\n" +
	"\rlocal_changes\x18\x02 \x03(\v2\x1c.medicore.users.UserTemplateR\flocalChanges\"\xa8\x01\n" +
	"\x15SyncTemplatesResponse\x12C\n" +
	"\x0eserver_updates\x18\x01 \x03(\v2\x1c.medicore.users.UserTemplateR\rserverUpdates\x12\x1f\n" +
	"\vdeleted_ids\x18\x02 \x03(\tR\n" +
	"deletedIds\x12)\n" +
	"\x10server_timestamp\x18\x03 \x01(\x03R\x0fserverTimestamp\"\x11\n" +
	"\x0fGetUsersRequest\">\n" +
	"\x10GetUsersResponse\x12*\n" +
	"\x05users\x18\x01 \x03(\v2\x14.medicore.users.UserR\x05users\"\x15\n" +
	"\x13GetTemplatesRequest\"R\n" +
	"\x14GetTemplatesResponse\x12:\n" +
	"\ttemplates\x18\x01 \x03(\v2\x1c.medicore.users.UserTemplateR\ttemplates\"#\n" +
	"\x11DeleteUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\".\n" +
	"\x12DeleteUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x15DeleteTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteTemplateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xb4\x06\n" +
	"\fUsersService\x12P\n" +
	"\tSyncUsers\x12 .medicore.users.SyncUsersRequest\x1a!.medicore.users.SyncUsersResponse\x12\\\n" +
	"\rSyncTemplates\x12$.medicore.users.SyncTemplatesRequest\x1a%.medicore.users.SyncTemplatesResponse\x128\n" +
	"\n" +
	"CreateUser\x12\x14.medicore.users.User\x1a\x14.medicore.users.User\x128\n" +
	"\n" +
	"UpdateUser\x12\x14.medicore.users.User\x1a\x14.medicore.users.User\x12S\n" +
	"\n" +
	"DeleteUser\x12!.medicore.users.DeleteUserRequest\x1a\".medicore.users.DeleteUserResponse\x12P\n" +
	"\vGetAllUsers\x12\x1f.medicore.users.GetUsersRequest\x1a .medicore.users.GetUsersResponse\x12L\n" +
	"\x0eCreateTemplate\x12\x1c.medicore.users.UserTemplate\x1a\x1c.medicore.users.UserTemplate\x12L\n" +
	"\x0eUpdateTemplate\x12\x1c.medicore.users.UserTemplate\x1a\x1c.medicore.users.UserTemplate\x12_\n" +
	"\x0eDeleteTemplate\x12%.medicore.users.DeleteTemplateRequest\x1a&.medicore.users.DeleteTemplateResponse\x12\\\n" +
	"\x0fGetAllTemplates\x12#.medicore.users.GetTemplatesRequest\x1a$.medicore.users.GetTemplatesResponseB\x1dZ\x1bmedicore-server/proto/usersb\x06proto3"

var (
	file_proto_users_proto_rawDescOnce sync.Once
	file_proto_users_proto_rawDescData []byte
)

func file_proto_users_proto_rawDescGZIP() []byte {
	file_proto_users_proto_rawDescOnce.Do(func() {
		file_proto_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_users_proto_rawDesc), len(file_proto_users_proto_rawDesc)))
	})
	return file_proto_users_proto_rawDescData
}

var file_proto_users_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_users_proto_goTypes = []any{
	(*User)(nil),                   // 0: medicore.users.User
	(*UserTemplate)(nil),           // 1: medicore.users.UserTemplate
	(*SyncUsersRequest)(nil),       // 2: medicore.users.SyncUsersRequest
	(*SyncUsersResponse)(nil),      // 3: medicore.users.SyncUsersResponse
	(*SyncTemplatesRequest)(nil),   // 4: medicore.users.SyncTemplatesRequest
	(*SyncTemplatesResponse)(nil),  // 5: medicore.users.SyncTemplatesResponse
	(*GetUsersRequest)(nil),        // 6: medicore.users.GetUsersRequest
	(*GetUsersResponse)(nil),       // 7: medicore.users.GetUsersResponse
	(*GetTemplatesRequest)(nil),    // 8: medicore.users.GetTemplatesRequest
	(*GetTemplatesResponse)(nil),   // 9: medicore.users.GetTemplatesResponse
	(*DeleteUserRequest)(nil),      // 10: medicore.users.DeleteUserRequest
	(*DeleteUserResponse)(nil),     // 11: medicore.users.DeleteUserResponse
	(*DeleteTemplateRequest)(nil),  // 12: medicore.users.DeleteTemplateRequest
	(*DeleteTemplateResponse)(nil), // 13: medicore.users.DeleteTemplateResponse
}
var file_proto_users_proto_depIdxs = []int32{
	0,  // 0: medicore.users.SyncUsersRequest.local_changes:type_name -> medicore.users.User
	0,  // 1: medicore.users.SyncUsersResponse.server_updates:type_name -> medicore.users.User
	1,  // 2: medicore.users.SyncTemplatesRequest.local_changes:type_name -> medicore.users.UserTemplate
	1,  // 3: medicore.users.SyncTemplatesResponse.server_updates:type_name -> medicore.users.UserTemplate
	0,  // 4: medicore.users.GetUsersResponse.users:type_name -> medicore.users.User
	1,  // 5: medicore.users.GetTemplatesResponse.templates:type_name -> medicore.users.UserTemplate
	2,  // 6: medicore.users.UsersService.SyncUsers:input_type -> medicore.users.SyncUsersRequest
	4,  // 7: medicore.users.UsersService.SyncTemplates:input_type -> medicore.users.SyncTemplatesRequest
	0,  // 8: medicore.users.UsersService.CreateUser:input_type -> medicore.users.User
	0,  // 9: medicore.users.UsersService.UpdateUser:input_type -> medicore.users.User
	10, // 10: medicore.users.UsersService.DeleteUser:input_type -> medicore.users.DeleteUserRequest
	6,  // 11: medicore.users.UsersService.GetAllUsers:input_type -> medicore.users.GetUsersRequest
	1,  // 12: medicore.users.UsersService.CreateTemplate:input_type -> medicore.users.UserTemplate
	1,  // 13: medicore.users.UsersService.UpdateTemplate:input_type -> medicore.users.UserTemplate
	12, // 14: medicore.users.UsersService.DeleteTemplate:input_type -> medicore.users.DeleteTemplateRequest
	8,  // 15: medicore.users.UsersService.GetAllTemplates:input_type -> medicore.users.GetTemplatesRequest
	3,  // 16: medicore.users.UsersService.SyncUsers:output_type -> medicore.users.SyncUsersResponse
	5,  // 17: medicore.users.UsersService.SyncTemplates:output_type -> medicore.users.SyncTemplatesResponse
	0,  // 18: medicore.users.UsersService.CreateUser:output_type -> medicore.users.User
	0,  // 19: medicore.users.UsersService.UpdateUser:output_type -> medicore.users.User
	11, // 20: medicore.users.UsersService.DeleteUser:output_type -> medicore.users.DeleteUserResponse
	7,  // 21: medicore.users.UsersService.GetAllUsers:output_type -> medicore.users.GetUsersResponse
	1,  // 22: medicore.users.UsersService.CreateTemplate:output_type -> medicore.users.UserTemplate
	1,  // 23: medicore.users.UsersService.UpdateTemplate:output_type -> medicore.users.UserTemplate
	13, // 24: medicore.users.UsersService.DeleteTemplate:output_type -> medicore.users.DeleteTemplateResponse
	9,  // 25: medicore.users.UsersService.GetAllTemplates:output_type -> medicore.users.GetTemplatesResponse
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_users_proto_init() }
func file_proto_users_proto_init() {
	if File_proto_users_proto != nil {
		return
	}
	file_proto_users_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_users_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_users_proto_rawDesc), len(file_proto_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_users_proto_goTypes,
		DependencyIndexes: file_proto_users_proto_depIdxs,
		MessageInfos:      file_proto_users_proto_msgTypes,
	}.Build()
	File_proto_users_proto = out.File
	file_proto_users_proto_goTypes = nil
	file_proto_users_proto_depIdxs = nil
}
